version: '3.1'

services:
#Create Nginx Proxy to 3 services

#Service 1 dimension
  dimension:
    build:
      context: .
      dockerfile: Dockerfile.dimension
    restart: always
    ports:
      - "8081:80"
#Service 2 editorial
  massively:
    build:
      context: .
      dockerfile: Dockerfile.massively
    restart: always
    ports:
      - "8082:80"
#Service 3 massively
  editorial:
    build:
      context: .
      dockerfile: Dockerfile.editorial
    restart: always
    ports:
      - "8083:80"